### ISSUE TITLE
"ModuleNotFoundError: No module named 'click'" when using `uvx`

### ISSUE THREAD

**Issue by twschiller** [OpenDataMCP/OpenDataMCP#9]
Thanks for this package! It looks like the [click dependency](https://pypi.org/project/click/) is missing from `pyproject.toml`: https://github.com/OpenDataMCP/OpenDataMCP/blob/main/pyproject.toml#L11

```
[14:57:21] λ uvx odmcp list
Traceback (most recent call last):
  File "/Users/username/.local/share/uv/tools/odmcp/bin/odmcp", line 5, in <module>
    from odmcp.cli import main
  File "/Users/username/.local/share/uv/tools/odmcp/lib/python3.13/site-packages/odmcp/cli.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

A workaround is use the [`--with` option](https://docs.astral.sh/uv/concepts/tools/#including-additional-dependencies) when installing/running the server with uv, e.g.: 

```bash
uv tool install --with click odmcp
```

**Comment by grll** [comment]
Hi @twschiller thanks for your interest in the project and reporting the issue I will have a look into it.
